package Controllers;

import GasStation.Employee;
import GasStation.GasStation;
import GasStation.Utilities;

import java.sql.*;

import java.util.ArrayList;
import java.util.Scanner;

/**
 * Controller handling databasde operations relating to Financial calculations
 */
public class FinancialController {

    /**
     * Returns the revenue of a specified gas station between the given days
     * @param gasStationID ID of gas station
     * @param start Earliest day to include revenue
     * @param end Final day to include revenue
     * @return The sum of all expenses at the gas station
     */
    public double getGasStationRevenue(int gasStationID, Date start, Date end){
        GasStation g = new GasStation(gasStationID);
        g.pull();
        return g.calculateStationRev(start, end);
    }

    /**
     * Calculates and returns the toal revenue generated by the gas chain for the given period
     * @param start  Earliest day to include revenue
     * @param end Final day to include revenue
     * @returnThe sum of all expenses in the entire chain
     */
    public double getChainRevenue(Date start, Date end){
        return GasStation.calculateChainRev(start, end);
    }


}
